# Generated by Django 5.0.2 on 2024-02-20 02:26

import django.core.validators
import patients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="document_photo",
            field=models.ImageField(
                upload_to="patient_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(
                max_length=255, validators=[patients.validators.validate_name]
            ),
        ),
    ]
